logging:
  pattern:
    console: " %d{yyyy-MM-dd HH:mm:ss.SSS}   %p %C{1} [%t]  %.-5120msg%n"
  level:
    com.prototype: DEBUG
    org.hibernate: ERROR
    org.springframework.security: INFO
    org.springframework.web: INFO