logging:
  pattern:
    console: " %d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level [%t] %C{1}  %.-5000msg%n"
  level:
    com.prototype: DEBUG
    org.hibernate: ERROR
    org.springframework.security: INFO
    org.springframework.web: INFO

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"